---
deployment:
  tasks:
    - export DEPLOYPATH=/home/nbnwetl3wxcr/public_html/
    - /bin/cp build/asset-manifest.json $DEPLOYPATH
    - /bin/cp build/favicon.ico $DEPLOYPATH
    - /bin/cp build/index.html $DEPLOYPATH
    - /bin/cp build/manifest.json $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp -R build/static $DEPLOYPATH
